# Basic GET test
GET https://mcsvoiceapp-bbg3d0f8gbb3gkd5.westus2-01.azurewebsites.net
###
#POST incoming call
POST https://13mhgtrx-49412.euw.devtunnels.ms/api/incomingCall

Content-Type: application/json

[
  {
    "Data": {},
    "Id": "885f973e-b4ee-4aac-bad3-2799a7e2de16_93984450f643468b8ba0dded4128b375.139774341",
    "Topic": "/subscriptions/63fa8a8e-d1fd-47ed-99f1-ec16d2d25d22/resourcegroups/copilotstudioservices/providers/microsoft.communication/communicationservices/lowcode-commservices",
    "Subject": "/phoneCall/caller/+436641927781/recipient/+13097392179",
    "EventType": "Microsoft.Communication.IncomingCall",
    "EventTime": "2025-08-21T11:35:55.6075231+00:00",
    "DataVersion": "1.0"
  }
]