---
config:
  layout: elk
  look: neo
  themeVariables:
    primaryColor: '#1b365d'
    secondaryColor: '#2176ff'
    tertiaryColor: '#dfe9f3'
    primaryBorderColor: '#2176ff'
    lineColor: '#6faaff'
    edgeLabelBackground: '#1c1e21'
---
flowchart TB
 subgraph UI["`🎨 **UI Layer**`"]
        M365["🧠 M365 Copilot"]
        AL["🤖 Agent Mode"]
        AB["🧩 Agent Builder"]
  end
 subgraph ORCH["🕹️ Orchestration Layer"]
        CS["📢 Copilot Studio Orchestrator Agent (Team Lead)"]
        SA1["🧭 Copilot Studio - Specialist Agent (Team Member)"]
        SA2["🧭 Copilot Studio - Specialist Agent 2 (Team Member 2)"]
  end

 subgraph SYS["⚙️ Integration (Tool) layer"]
        FT["🏗️ Azure Foundry SDKs"]
        AIM["🔍 HHosted LLMs"]
        AZS["Azure Services"]
        TOOL["🛠️ Tool"]
        API["🔗 API Interface"]
        MCP["📡 MCP"]
        CWS["🧰 CUA"]
        A2A["🔄 A2A"]
        JOULE["💡 Joule"]
        AF["🧑‍✈️ Agentforce"]
        EXT["🌐 Other Agent FX"]
  end

 subgraph BIZ["Microsoft Business Agents"]
      
        SALES["💰 Sales agent"]
        SERVICE["🛎️ Service agent"]
        MARK["📣 Marketing agent"]
        ESS["👥 Employee Self Service agent"]

  end
 subgraph KNO["Knowledge Layer"]
        WIQ["🧠 WorkIQ"]
        AIM["🔎 Foundry Hosted LLMs"]
        KNOC["🏥 LOB Knowledge Connectors"]
  end
subgraph APP["App Layer (Apps in Chat)"]
      MCPAPPS["MCP Apps"]
      PA["Power Apps"]
      OAIAPP["OpenAI App SDK"]
end

 subgraph A365["💼 Agent 365"]
        ORCH
        SYS
        UI
        BIZ
        KNO
        APP
  end 


    M365 -- Edit office files --> AL
    M365 -- Simple retrieval agents --> AB
    UI -- Extended by --> ORCH & BIZ
    BIZ -- Extended by --> ORCH
    ORCH -- "Orchestrating other agents" --> A2A
    ORCH -- "Orchestrating hosted services" --> FT
    ORCH -- "Orchestrating own tools" --> TOOL
    ORCH -- "Surfacing knowledge" --> KNO
    ORCH -- "Displays forms" --> APP
    CS -- "1..n" --> SA1 & SA2
    FT -- Indexed knowledge --> AIM
    TOOL -- API call --> API
    TOOL -- Data stream --> MCP
    TOOL -- Integration --> CWS
    A2A -- "Calls agents" --> JOULE & AF & EXT
    FT -- Exposing --> AZS
    